name: Build Windfall

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Setup C++ Compiler
        if: runner.os == 'Windows'
        run: choco install mingw -y
      - name: Set up C++ compiler
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Set up C++ compiler
        if: runner.os == 'macOS'
        run: brew install gcc
      
      - name: Build C++ backend
        run: |
          mkdir -p build
          if ls src/*.cpp 1> /dev/null 2>&1; then
          clang++ src/*.cpp -o build/windfall_backend
          else
          echo "No C++ files to compile, skipping."
          fi
        
      - name: Package Python GUI
        run: |
          pyinstaller --onefile --name Windfall main.py

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windfall-${{ runner.os }}
          path: |
            build/windfall_backend
            dist/Windfall*

